[general]
framerate = 60
bars = 40
autosens = 0
sensitivity = 100
scaling = linear

[output]
method = raw
channels = mono
mono_option = average
reverse = 0
raw_target = /dev/stdout
data_format = binary
bit_format = 16bit

[smoothing]
monstercat = 0
waves = 0
noise_reduction = 0
